Resources:
  ##########################################
  # API Endpoints
  ##########################################
  WorkflowApi:
    Type: 'AWS::Serverless::Api'
    Properties:
      Name: WorkflowApi
      StageName: "beta"
      DefinitionBody:
        swagger: "2.0"
        info:
          version: '1.0'
          title:
            Ref: 'AWS::StackName'
        schemes:
        - "https"
        definitions:
          Empty:
            type: "object"
            title: "Empty Schema"
        securityDefinitions:
          sigv4:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: awsSigv4
        paths:
          /workflow:
            post:
              produces:
              - "application/json"
              security:
              - sigv4: []
              responses:
                "200":
                  description: "200 response"
                  schema:
                    $ref: "#/definitions/Empty"
              x-amazon-apigateway-integration:
                uri:
                  Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${StartWorkflowAPIGLambdaFunction}/invocations'
                responses:
                  default:
                    statusCode: "200"
                passthroughBehavior: "when_no_match"
                httpMethod: "POST"
                type: "aws_proxy"
      Cors:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'86400'"